minimumReleaseAgeExclude:
  - '@neuralfog/elemix-compiler-darwin-arm64@0.0.0-dev'
  - '@neuralfog/elemix-compiler-darwin-x64@0.0.0-dev'
  - '@neuralfog/elemix-compiler-linux-arm64@0.0.0-dev'
  - '@neuralfog/elemix-compiler-linux-x64@0.0.0-dev'
  - '@neuralfog/elemix-compiler-win32-arm64@0.0.0-dev'
  - '@neuralfog/elemix-compiler-win32-x64@0.0.0-dev'
  - '@neuralfog/elemix-compiler@0.0.0-dev'
  - '@neuralfog/elemix-compiler-darwin-arm64@0.0.0-dev.1'
  - '@neuralfog/elemix-compiler-darwin-x64@0.0.0-dev.1'
  - '@neuralfog/elemix-compiler-linux-arm64@0.0.0-dev.1'
  - '@neuralfog/elemix-compiler-linux-x64@0.0.0-dev.1'
  - '@neuralfog/elemix-compiler-win32-arm64@0.0.0-dev.1'
  - '@neuralfog/elemix-compiler-win32-x64@0.0.0-dev.1'
  - '@neuralfog/elemix-compiler@0.0.0-dev.1'
